### ISSUE TITLE
fmerge error

### ISSUE THREAD

**Issue by wilburtownsend** [sergiocorreia/ftools#21]
I just received the following error when using fmerge. I suspect I hit some sort of memory limit.

```
fmerge m:1 perm using "`permutations'", assert(match) nogen
                  join():  3900  unable to allocate real <tmp>[403200000,9]
                 <istmt>:     -  function returned error
r(3900);                                                                                                     
```

Here's version number:
```
which ftools             
/home/wtownsend/ado/plus/f/ftools.ado
SMP Mon Jun 25 08:07:07 PDT 
*! version 2.24.3 24jan2018 
```

Here's the dofile, for context
https://pastebin.com/NixsYupi

**Comment by wilburtownsend** [comment]
I received a similar bug using fcollapse
```
 fcollapse (sum) value, by(r)
                 round():  3900  unable to allocate real <tmp>[403200000,1]
                factor():     -  function returned error
                 <istmt>:     -  function returned error
```

**Comment by sergiocorreia** [comment]
This is a stata error that happens when it runs out of memory. In your case, you were trying to allocate a vector with 400mm obs and Stata couldn't do it.

400m obs, with 8 bytes per observations, is roughly 3.2 gigabytes, on top of all the memory that stata and Mata are already using. If you are on a server that shouldn't be a problem, but on a laptop or desktop you will probably run out of memory.

One option is that you can try closing other programs, or dropping unused obs. and variables (or using compress), to save memory before the collapse.

Also, it might help to update ftools to the latest versions.

**Comment by asmithbravo** [comment]
Dear Sergio,

After running xtabond2 for a dynamic panel data model I get the same message:

round():  3900  unable to allocate real <tmp>[403200000,1]
                factor():     -  function returned error
                 <istmt>:     -  function returned error

Could I use tools to estimate xtabond2 and solve the memory problem When I add the nomata option, the system tells me the following message:

no room to add more variables Up to 5,000 variables are currently allowed, although you could reset the maximum using set maxvar; see help memory.]

Do you know how to solve this_ Could I use your package?

Thanks

**Comment by sergiocorreia** [comment]
As mentioned in the other thread, this is likely due to your computer's memory being too small for whatever xtabond2 needs. vectors of size 400m*1 are HUGE, so you either need a beefy server, a smaller dataset, or understand a bit better what's causing this allocation
