### ISSUE TITLE
Dict size exceeds Mata limits?

### ISSUE THREAD

**Issue by fburlig** [sergiocorreia/ftools#28]
Hi Sergio,
I'm running into a `dict size exceeds Mata limits` error running `reghdfe`  on a pretty large dataset, and found this error built into the `ftools` .ado file. 

According to the Stata [documentation ](https://blog.stata.com/2019/06/26/stata-16-released/)for the release of Stata 16, though, "Mata matrices remain limited only by memory," so I was wondering if there's a remaining reason for the hard-coded limit in place here?

Thanks!

**Comment by sergiocorreia** [comment]
Hi Fiona,

What's the size of your dataset?

I suspect you might have run into a check that ensures that -long- variable types are enough to fit group identifiers. If there are more than ~2 billion obs (or was it 1 billion?) then long stops being good enough and we have to use doubles.

Beyond that, the problem is that I'm not 100% sure that nothing breaks beyond that:

1. I haven't tested ftools on datasets that large, and adding tests for those cases is tricky (I would need a server just for testing).
2. Until recently, Stata itself didn't work with datasets beyond 1bn obs.

Finally, if you run reghdfe with the verbose (1) option, where exactly is the error? 

Best,
Sergio

**Comment by jessebu93** [comment]
Hi Sergio,

Fiona's grad student here. A couple of details that might be helpful:
- We have just under 1.7 billion observations here.
- The group identifiers are float variables
- The dependent variable is double
- The independent variables are float or double
- The fixed effects are double and float.

The error occurs in initializing the Mata object for the three fixed effects.

<img width="784" alt="Screen Shot 2020-02-18 at 4 20 31 PM" src="https://user-images.githubusercontent.com/50382134/74789988-e71b4300-527b-11ea-8084-51867193f2af.png">

Thanks for your help!

Best,
Jesse

**Comment by sergiocorreia** [comment]
I found out more about the issue. It [seems](https://www.statalist.org/forums/forum/general-stata-discussion/mata/325388-limit-on-maximum-matrix-length-from-j) that indeed earlier versions of Stata did not support more than `2^31` Mata rows.

So, assuming you are using Stata 16 or so, one option you have is to maybe fork ftools and comment out [this line](https://github.com/sergiocorreia/ftools/blob/4d6e83bac1ccb440463aa032c28912017b3cba7f/src/ftools_main.mata#L597), to see if it works (caveat emptor).

However, it might be possible to get it to run without having to change the code. For this you need to know some details:

---

When ftools computes a group identifier for the triple `sp_id mofy hour`, it needs a vector with *at least* K rows, where K is the number of levels of those variables (jointly). Because we don't know K, it relies on heuristics to get upper bounds. For instance:

1) If all three variables are of `byte` type (max 256 levels each) then K is at most `256^3=16.7mm`, which is a reasonable size. Similarly, if the minimum value of "hour" is 1 and the maximum is 24, then we can use even tighter bounds.
2) For larger group types (int, long) this lower bound becomes non-binding, so as a last resource I just use the size of the data, which is the issue with your case.

---

Thus, there are two things you can do which might fix the problem:

1) Compress the float identifiers to byte/int/long. There is **no reason** to have float identifiers (see `help data_types`) and doing so makes most computations slower. For instance, if ftools sees that something is a float, then it will not be able to use any of the heuristics and will end up using a lot of memory. So for sure do this change no matter what.
2) Create the group identifiers outside of reghdfe. For instance, `gegen double group id = group(sp_id mofy hour)` (using the gtools package). Also remember to compress the identifiers afterwards.

Best,
Sergio

**Comment by fburlig** [comment]
Thanks, @sergiocorreia! Those suggestions seem to have solved the problem. Now we're just running into actual machine memory limits :)

**Comment by sergiocorreia** [comment]
> Thanks, @sergiocorreia! Those suggestions seem to have solved the problem. Now we're just running into actual machine memory limits :)

If it helps, check out the email I sent to Dan Feenberg quoted here: http://www.nber.org/stata/efficient/multiple-fixed-effects.html

If you keep only the variables that you need, use the correct data types (e.g. never use float when you can use byte as float takes 4x the space), and use the compact and pool(#) options for # small (e.g. start at 4 and reduce as needed), then it should fit. You might also want to use less strict tolerances and a verbose(1) option to see what's going on while you wait.
