### ISSUE TITLE
Command join is unrecognised

### ISSUE THREAD

**Issue by glennmagerman** [sergiocorreia/ftools#7]
Hi,

first of all, thanks a lot for both ftools and reghdfe! These are superb tools...

I have an issue using Stata 14 and using fmerge: I get an error r(199) stating "command join is unrecognised".
I have ftools also running on a Stata 13 version and there I have no issues.
All the best,
Glenn

**Comment by sergiocorreia** [comment]
Hi Glenn,

Did you install ftools from SSC or Github, and when? Also, what version are you using? This is what I see on my side:

```
. which ftools
c:\ado\plus\f\ftools.ado
*! version 2.9.2 06apr2017
```

At some point a few weeks ago, the SSC version of ftools had some missing files (namely, those that didn't start with "f") so I wouldn't be surprised if that was related.

Can you try this, just in case:

```
ado uninstall ftools
net install ftools, from(https://github.com/sergiocorreia/ftools/raw/master/src/)
ftools, compile
```

Cheers,
S

**Comment by glennmagerman** [comment]
Hi Sergio,

thank you for the quick reply. I think I see the issue:
I downloaded the ado today on my laptop (*! version 2.9.2 06apr2017)
I then copied the files in the ado folder "f" to a server which has no access to the internet. 
However, I was not aware that it would also copy files into other folders. 
Just to be sure, I thus copy the following ado files to the restricted server: fegen, fcollapse, join, fisid, fsort and moremata?

Apologies for asking another very basic question, but I would like to add count() and total() to the fegen functions. I saw your entry in the help file, could you point me to a document with a bit more intermediate explanation on how to do this?
Thank you very much,
Glenn

**Comment by sergiocorreia** [comment]
If you have no internet access, it's best to download the [ZIP file(https://github.com/sergiocorreia/ftools/archive/master.zip) and extract all the files in the `src` folder to a folder in the computer. Then you can run `net install ftools, from(SOME_FOLDER)`

(First be sure that you deleted the files you copied by hand, sometimes that causes problems)

Alternatively, just copy all the files in the `src` folder by hand, but there are quite a few: https://github.com/sergiocorreia/ftools/tree/master/src (they all start with `f` or `m`, except for `join.*`).

For your other question, if you want something like egen total:

```
sysuse auto
fcollapse (sum) price, by(turn) fast merge
```

That will collapse and merge it back quickly so it works the same (but fast). Similarly, you can use `fcollapse (count) ....` instead of egen count

**Comment by glennmagerman** [comment]
Hi Sergio,

apologies for the tardy reply. Everything works like a charm!
The fcollapse is simply amazing...
And also I really like the explicit signalling in fmerge if variables already exist in the master dataset, something that's missing in the baseline Stata command!
Happy to send you a draft of the paper we're working on when available, relying a lot on both reghdfe and ftools...
Thank you, 
Glenn

**Comment by sergiocorreia** [comment]
Great to hear that, and sure, feel free to share it whenever you can!

Cheers,
Sergio
